# Generated by Django 4.0.2 on 2022-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('typeOfTask', models.CharField(choices=[('finished', 'finished'), ('pending', 'pending'), ('overdue', 'overdue')], max_length=255)),
                ('isComplete', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
